const states={AC:["Rio Branco","Cruzeiro do Sul"],AL:["Maceió","Arapiraca"],AP:["Macapá","Santana"],AM:["Manaus","Parintins"],BA:["Salvador","Feira de Santana","Vitória da Conquista"],CE:["Fortaleza","Caucaia","Juazeiro do Norte"],DF:["Brasília"],ES:["Vitória","Vila Velha","Serra"],GO:["Goiânia","Aparecida de Goiânia"],MA:["São Luís","Imperatriz"],MT:["Cuiabá","Várzea Grande"],MS:["Campo Grande","Dourados"],MG:["Belo Horizonte","Uberlândia","Contagem"],PA:["Belém","Santarém"],PB:["João Pessoa","Campina Grande"],PR:["Curitiba","Londrina","Maringá"],PE:["Recife","Caruaru","Olinda"],PI:["Teresina","Parnaíba","Picos"],RJ:["Rio de Janeiro","Niterói","Petrópolis"],RN:["Natal","Mossoró"],RS:["Porto Alegre","Caxias do Sul"],RO:["Porto Velho","Ji-Paraná"],RR:["Boa Vista"],SC:["Florianópolis","Joinville","Blumenau"],SP:["São Paulo","Campinas","Santos","Ribeirão Preto"],SE:["Aracaju","Nossa Senhora do Socorro"],TO:["Palmas","Araguaína"]};
const stateNames={AC:"Acre",AL:"Alagoas",AP:"Amapá",AM:"Amazonas",BA:"Bahia",CE:"Ceará",DF:"Distrito Federal",ES:"Espírito Santo",GO:"Goiás",MA:"Maranhão",MT:"Mato Grosso",MS:"Mato Grosso do Sul",MG:"Minas Gerais",PA:"Pará",PB:"Paraíba",PR:"Paraná",PE:"Pernambuco",PI:"Piauí",RJ:"Rio de Janeiro",RN:"Rio Grande do Norte",RS:"Rio Grande do Sul",RO:"Rondônia",RR:"Roraima",SC:"Santa Catarina",SP:"São Paulo",SE:"Sergipe",TO:"Tocantins"};
const cats=["Burgueria","Hamburgueria","Restaurante","Pizzaria","Lanchonete","Padaria","Mercado","Loja de roupas","Loja de calçados","Barbearia","Salão de beleza","Clínica","Academia","Oficina","Autopeças","Hotel","Pousada","Imobiliária","Escritório","Contabilidade","Advocacia","Dentista","Farmácia","Pet shop","Veterinária","Escola","Curso","Agência","Fotógrafo","Eventos","Construtora","Eletricista","Encanador","Mecânico","Marcenaria","Empresa de tecnologia","Serviços profissionais","Outros"];
const opportunities=["Sem site","Site desatualizado","Precisa de redesign","Landing page","Loja virtual","Cardápio online","Catálogo digital","Página profissional","Sistema web","Presença digital","Melhorar presença online","Site responsivo","Outros"];
const state=document.getElementById("state"),city=document.getElementById("city"),category=document.getElementById("category"),opp=document.getElementById("opportunityOptions");
Object.entries(stateNames).forEach(([k,v])=>state?.insertAdjacentHTML("beforeend",`<option value="${k}">${v}</option>`));
cats.forEach(v=>category?.insertAdjacentHTML("beforeend",`<option>${v}</option>`));
opportunities.forEach((v,i)=>opp?.insertAdjacentHTML("beforeend",`<label><input type="checkbox" value="${v}" ${i===0?"checked":""}>${v}</label>`));
state?.addEventListener("change",()=>{city.innerHTML='<option value="">Todo o estado</option>';(states[state.value]||[]).forEach(c=>city.insertAdjacentHTML("beforeend",`<option>${c}</option>`));city.disabled=!state.value});
const sampleNames=["Burger House","Studio Bella","Auto Center Prime","Pizzaria Central","Clínica Vida","Barbearia Alpha","Mercado Bom Preço","Imobiliária Horizonte","Academia Evolution","Marcenaria Nova Forma","Pet Center","Oficina Master"];
function mockResults(catName,location,opts,count){return Array.from({length:Math.min(count,12)},(_,i)=>({id:crypto.randomUUID(),name:`${catName||sampleNames[i%sampleNames.length]} ${i+1}`,category:catName||["Hamburgueria","Restaurante","Serviços"][i%3],location,address:`Endereço fornecido pela API • ${location}`,phone:`+55 11 9${String(80000000+i).padStart(8,"0")}`,website:null,opportunity:opts[i%Math.max(opts.length,1)]||"Sem site",source:"DEMO_LOCAL — substituir por API real"}))}
function approach(l,plan){if(plan==="FREE")return `Olá! Tudo bem? Encontrei o perfil da ${l.name} e percebi uma oportunidade de melhorar sua presença online. Trabalho com criação de sites profissionais e gostaria de mostrar uma ideia que poderia ajudar seu negócio.`;return `Olá! Tudo bem? Encontrei a ${l.name}, ${l.category}, em ${l.location}. Notei uma oportunidade de fortalecer a presença digital da empresa${l.website?"":" com um site profissional"}. Trabalho com criação de sites e posso apresentar uma ideia personalizada para o negócio. Podemos conversar?`}
function renderResults(results){const box=document.getElementById("results");box.innerHTML=results.map(l=>`<article class="lead-card"><div class="lead-head"><h3>${escapeHTML(l.name)}</h3><span class="badge">SEM SITE</span></div><div class="lead-meta">${escapeHTML(l.category)}<br>${escapeHTML(l.location)}<br>${escapeHTML(l.address)}<br>Telefone: ${escapeHTML(l.phone)}</div><div class="lead-actions"><a class="btn wa" target="_blank" href="https://wa.me/${l.phone.replace(/\D/g,"")}">WhatsApp</a><button class="btn" onclick='showApproach(${JSON.stringify(l)})'>Abordagem</button><button class="btn" onclick='saveLead(${JSON.stringify(l)})'>Salvar</button></div></article>`).join("")}
function showApproach(l){const u=getUser();const m=approach(l,u.plan);if(confirm(m+"\n\nCopiar abordagem?"))navigator.clipboard?.writeText(m)}
function saveLead(l){const u=getUser();u.saved=u.saved||[];if(!u.saved.some(x=>x.id===l.id))u.saved.push(l);LF_STORE.set("user",u);renderSaved()}
function renderSaved(){const box=document.getElementById("savedLeads"),u=getUser();box.innerHTML=u.saved?.length?u.saved.map(l=>`<div class="saved-item"><div><b>${escapeHTML(l.name)}</b><small>${escapeHTML(l.category)} • ${escapeHTML(l.location)}</small></div><span class="badge">NOVO</span></div>`).join(""):'<div class="empty">Nenhum lead salvo ainda.</div>'}
function renderHistory(){const box=document.getElementById("historyList"),u=getUser();box.innerHTML=u.searches?.length?u.searches.slice().reverse().map(s=>`<div class="history-item"><div><b>${escapeHTML(s.city||"Todo o estado")} • ${escapeHTML(s.state)}</b><small>${escapeHTML(s.category||"Todos os segmentos")} • ${s.results.length} leads • ${s.credits} créditos</small></div><small>${new Date(s.date).toLocaleString("pt-BR")}</small></div>`).join(""):'<div class="empty">Nenhuma pesquisa realizada.</div>'}
document.getElementById("leadSearchForm")?.addEventListener("submit",async e=>{e.preventDefault();const u=getUser();if(u.credits<6){alert("Seus créditos acabaram. Faça upgrade do plano para continuar.");location.href="planos.html";return}const opts=[...document.querySelectorAll("#opportunityOptions input:checked")].map(x=>x.value);const loading=document.getElementById("loading"),results=document.getElementById("results");loading.classList.remove("hidden");results.innerHTML="";await new Promise(r=>setTimeout(r,900));const loc=`${city.value||"Todo o estado"} - ${state.value||"Brasil"}`;const max=LF_CONFIG.plans[u.plan]?.maxResults||6;const r=mockResults(document.getElementById("customCategory").value||category.value,loc,opts,max);u.credits-=6;u.searches=u.searches||[];u.searches.push({date:new Date().toISOString(),state:stateNames[state.value]||"Brasil",city:city.value,category:category.value,filters:opts,credits:6,results:r});LF_STORE.set("user",u);loading.classList.add("hidden");renderResults(r);refreshStats();renderHistory()});
renderSaved();renderHistory();